### ISSUE TITLE
Mac OS ARM installation

### ISSUE THREAD

**Issue by keflavich** [interstellarmedium/HI_telescope#2]
I've been working on installing on Mac OS 13.6 with an M1 Max processor.  There are a few hurdles:

 * I installed the requirements with conda.  Using `conda-forge`, I installed the following packages:
```
gnuradio==3.8* airspy airspyhf boost-cpp click click-plugins cmake codec2 cppzmq cxx-compiler fftw gtk3 gmp gsl libad9361-iio libcblas libiio libsndfile log4cpp lxml mako ninja numpy pkg-config pybind11 pybind11-abi pygobject pyqt python pyyaml qt qwt sdl soapysdr spdlog uhd volk zeromq packaging swig h5py ephem matplotlib gnuradio-osmosdr
```
 * For the cmake build, I do the following:
```
export CFLAGS=-arch=arm64
mkdir build
cd build
cmake -DCMAKE_OSX_ARCHITECTURES=arm64 ..
make
```

That gets me to:
```
[ 14%] Building CXX object lib/CMakeFiles/gnuradio-radio_astro.dir/dedispersion_impl.cc.o
[ 28%] Building CXX object lib/CMakeFiles/gnuradio-radio_astro.dir/detect_impl.cc.o
[ 42%] Building CXX object lib/CMakeFiles/gnuradio-radio_astro.dir/vmedian_impl.cc.o
[ 57%] Linking CXX shared library libgnuradio-radio_astro.dylib
[ 57%] Built target gnuradio-radio_astro
[ 57%] Built target radio_astro_swig_swig_doc
[ 71%] Swig source radio_astro_swig.i
swig error : Unrecognized option -relativeimport
Use 'swig -help' for available options.
make[2]: *** [swig/CMakeFiles/radio_astro_swig.dir/radio_astro_swigPYTHON.stamp] Error 1
make[2]: *** Deleting file `swig/CMakeFiles/radio_astro_swig.dir/radio_astro_swigPYTHON.stamp'
make[1]: *** [swig/CMakeFiles/radio_astro_swig_swig_compilation.dir/all] Error 2
make: *** [all] Error 2
```

@interstellarmedium any idea if there's a specific version of swig required to enable relative imports?

**Comment by keflavich** [comment]
Add `swig` to the list of installed modules; i was using a super old swig (2.0) while 4.x is needed.

**Comment by keflavich** [comment]
Also add `h5py ephem`; those appear to be runtime requirements

**Comment by keflavich** [comment]
I added a few more by editing the original post.

I'm still stuck with my hardware not being recognized.
<img width="1184" alt="image" src="https://github.com/user-attachments/assets/bae1a772-2443-47ee-bb7c-8c9d77c279bf">

**Comment by ism-book** [comment]
I vaguely remember seeing a similar problem but unfortunately I can't remember what I did to fix it (if indeed that was the error). gnuradio is fairly finicky and goes through frequent updates. Sorry I can't help - I got it working on the computer I use for the radio telescope a long time ago and don't want to mess with it! Plus you understand software better than me @keflavich :)

**Comment by keflavich** [comment]
Dang, ok.  I got the computer to recognize the device and record data, but gnuradio still wouldn't.

This command worked:
```
airspy_rx -r test_airspy_rx -f 1420 -a 10000000 -t 1 -n 10000000
```

so if you can think of any last tricks required for gnuradio to recognize it, that'd be super helpful. Otherwise, I can probably maybe figure out how to use that command to record data.

**Comment by ism-book** [comment]
Classes start next week so this is not the best timing for me, but I'll try to take a look asap and will get back to you

**Comment by keflavich** [comment]
No worries, I'll figure something out.   I think the `airspy_rx` command records data at the desired rate and frequency, I just need to test it with an LNA and a telescope attached to verify it on sky.

**Comment by keflavich** [comment]
if you figure out a solution, I'll try it out, but I've found a workaround to just use the `airspy_rx` command as above directly. I'll try copying the appropriate parameters (gain etc) from your code.

**Comment by ism-book** [comment]
Hey Adam, I was able to get gnuradio working with airspy ok on my new mac. I got some errors and was about to go down the software route when I double-checked my connections and used a new usb-c to usb-a connector to the airspy and, magically, everything worked! So I don't have a lot of helpful advice for you other than to check the connections!
